import Head from 'next/head';

import Layout from '../components/layouts/Layout';

import type { NextPage } from 'next';

const Home: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="container">
        {Array.from({ length: 20 }).map((_, idx) => (
          <p key={idx} className="text-lg my-4">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore
            delectus distinctio magni voluptatum odit sint officia dolor!
            Maiores adipisci sit sunt, mollitia sapiente iusto id doloribus
            dolore. Error necessitatibus et delectus. Rem eaque accusantium
            beatae officia quibusdam sed similique delectus nostrum sint
            quaerat? Totam dolor laudantium delectus accusamus assumenda ipsam.
          </p>
        ))}
      </div>
    </Layout>
  );
};

export default Home;
